# Ref: https://docs.docker.com/build/ci/github-actions/
name: Build Docker Image for runai-pytorch-mnist

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - .github/workflows/build_pytorch_mnist.yaml
      - thirdparty/**
      - scripts/docker/run.sh
      - Dockerfile_pytorch_mnist
      - .dockerignore

jobs:
  docker:
    if: github.repository == 'j3soon/runai-isaac'
    runs-on: ubuntu-latest
    steps:
      -
        name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          build-mount-path: /var/lib/docker/
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      -
        name: Restart docker
        run: sudo service docker restart
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        # Ref: https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-a-registry-using-a-personal-access-token
        name: Prepare tag name as environment variable
        run: |
          # This strips the git ref prefix from the version.
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # This strips the "v" prefix from the tag name.
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=-$(echo $VERSION | sed -e 's/^v//')
          # This doesn't use the Docker `latest` tag convention.
          [ "$VERSION" == "main" ] && VERSION=""
          # Output the environment variable
          # Ref: https://stackoverflow.com/a/57989070
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      -
        name: Docker meta
        id: meta
        # Ref: https://github.com/docker/metadata-action
        uses: docker/metadata-action@v5
        with:
          # Link: https://hub.docker.com/repository/docker/j3soon/runai-pytorch-mnist/tags
          images: ${{ secrets.DOCKERHUB_USERNAME }}/runai-pytorch-mnist
          tags: |
            type=raw,value=latest-{{ date 'YYYYMMDD' }}
            type=raw,value=latest${{ env.VERSION }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile_pytorch_mnist
          push: true
          tags: ${{ steps.meta.outputs.tags }}
